### ISSUE TITLE
STD5 / STD10 / English Dunya

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#304]
As part of a partnership development with Zaya we would need three zim files for them to showcase using the Kiwix-hotspot to various ministries
A google sheet with file name, description, path, etc. is here
https://docs.google.com/spreadsheets/d/1EZn3XkXE9fQ19ZlEYvnLao7n6aYxTBLSx0n2V6bbnkk/edit?usp=sharing
(there are three tabs, one in English and two in Marathi)

The source files are here:
https://drive.google.com/drive/folders/18MX_bNzwA7_NnxpM66QkOvqd7kGIxGWv?usp=sharing

Descriptions:
**Std 5 SSC English**: Videos and Textbook for Standard 5 SSC applicable in Maharashtra.
**Std 10 SSC Marathi**: Videos and Textbook for Standard 10 SSC applicable in Maharashtra.
In both cases the logo would be this one:

![Diksha logo](https://user-images.githubusercontent.com/21675885/97893150-32ee1980-1d31-11eb-80af-7e550cf3bff9.jpeg)

**English Duniya - Marathi**: ज़ाया इंग्लिश दुनिया मराठी - हा मराठी भाषिकांसाठी इंग्रजी शिकण्याचा एक मजेदार मार्ग आहे
Logo:
![English Duniya logo](https://user-images.githubusercontent.com/21675885/97893174-3a152780-1d31-11eb-93d2-66228720a9d1.jpg)

**Comment by rgaudin** [comment]
- Recipe: [diksha-std10ssc-marathi](https://farm.openzim.org/recipes/diksha-std10ssc-marathi)
- ZIM: [diksha-std5ssc_en_2020-11.zim](http://download.kiwix.org/zim/.hidden/dev/diksha-std5ssc_en_2020-11.zim)


- Recipe: [diksha-std5ssc-english](https://farm.openzim.org/recipes/diksha-std5ssc-english)
- ZIM: [diksha-std10ssc_mr_2020-11.zim](http://download.kiwix.org/zim/.hidden/dev/diksha-std10ssc_mr_2020-11.zim)

- Recipe: [zaya-english-duniya-marathi](https://farm.openzim.org/recipes/zaya-english-duniya-marathi)
- ZIM: [zaya-english-duniya-marathi_mr_2020-11.zim](http://mirror.download.kiwix.org/zim/.hidden/dev/zaya-english-duniya-marathi_mr_2020-11.zim)

Once it's validated and recipe names and ZIM file names are confirmed, we can move out of /dev and relaunch.

**Comment by Popolechien** [comment]
Looks like there is a problem with (see screenshots):
- some videos that do not work (actually none does on `diksha-std10ssc-marathi`)
- PDF files that can not be open (though this I suspect comes from my phone's settings).
![Screenshot_20201112_152047_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/98952736-148bd900-24fc-11eb-8050-50728db09bd1.jpg)
![Screenshot_20201112_152027_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/98952745-1786c980-24fc-11eb-9368-b045904d792c.jpg)

**Comment by rgaudin** [comment]
Ah yes forgot to redo the 10 package when I fixed it. will update.
pdf thing is you have no reader on your phone

**Comment by Popolechien** [comment]
*Question:* Is there a specific format to replace the Nautilus banner on top of the content list?

As for PDF I've also tested it on Mac and the one from STD10 would not open. I do have a PDF reader btw on my phone so it's more a matter of Kiwix-Android not picking it up.

**Comment by rgaudin** [comment]
For std10, all links are broken.

For banner, prepare an image file of same dimensions and add to recipe

**Comment by Popolechien** [comment]
ok - what are the dimensions required?

**Comment by Popolechien** [comment]
> For std10, all links are broken.

What do you mean exactly? Those in the google drive work.

**Comment by rgaudin** [comment]
@Popolechien the nautilus logo is at https://github.com/openzim/nautilus/blob/master/nautiluszim/templates/assets/main-logo.png

You know you can change the colors in the recipe as well.

I fixed the archive for std10 and recreated the ZIM. please re-download the ZIM from the link above. Should work fine now.

**Comment by Popolechien** [comment]
All videos are good, thanks. Will move from /dev to /other

**Comment by Popolechien** [comment]
Two of the videos in the [STD5](https://library.kiwix.org/diksha-std5ssc_en_2020-11) do not work: _On the water_ and _Count your garden_

I've looked at the [source files](https://drive.google.com/drive/folders/1y3VERUxjecC92tdlUUikQiuTlB8xeF1C) and both are ok, but then both also have a special character (`#SWEET`) in the filename. Could this be the issue?

**Comment by rgaudin** [comment]
Called URL (not working): https://library.kiwix.org/diksha-std5ssc_en_2020-11/I/files/On%20The%20Water%20_%20Std.5th(H.L.)%20_%20English%20Poem%20_%20Recited%20by%20Angel%20R.%20Bhalerao%20#SWEET%20OJAL.mp4

Encoded `#` (working): https://library.kiwix.org/diksha-std5ssc_en_2020-11/I/files/On%20The%20Water%20_%20Std.5th(H.L.)%20_%20English%20Poem%20_%20Recited%20by%20Angel%20R.%20Bhalerao%20%23SWEET%20OJAL.mp4

**Comment by rgaudin** [comment]
Fixed in https://mirror.download.kiwix.org/zim/other/diksha-std5ssc_en_2020-11.zim

**Comment by Popolechien** [comment]
Both videos seem to still not be working. Tried on library.kiwix.org and kiwix-desktop.

**Comment by rgaudin** [comment]
Videos work fine on kiwix-serve. We agreed we'll reencode the videos so the result is more predictable but unrelated issues won't magically disappear. library.kiwix.org is apparently using an different version of the ZIM

**Comment by rgaudin** [comment]
Done. Please remember to clean the browser when testing with same URL as the collection is stored in the browser. You can easily check that you're getting the new version by looking at filenames (`.webm` now)

**Comment by Rexadev** [comment]
@rgaudin Edit description to `India, Maharashtra 5th Class SSC Books & Videos`
