### ISSUE TITLE
Alexandria boardgames

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#659]
- Website URL: https://alexandria.dk/
- License: **Creative Commons ** (see https://twitter.com/peterbrodersen/status/1661086896682876951)
- Desired ZIM Title: **Alexandria boardgames**
- Desired ZIM Description: A library for role-playing games, board games, and the likes
- Desired ZIM Icon –png (URL or attach one): https://alexandria.dk/gfx/texture_logo.gif
- Language (ISO 639-3): **eng** (several languages in fact, this may need playing a bit with settings to see if we can capture /en /dk and others separately)
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment]
I've created a recipe for english only
https://farm.openzim.org/recipes/alexandria.dk_en_all
@rgaudin @benoit74 can advise which settings shall I play with to capture different languages?

**Comment by rgaudin** [comment]
URLs seems to be prefixed with the language: `/en/`, `/sv/`, etc. Have you tried?

**Comment by RavanJAltaie** [comment]
@rgaudin I tried your suggestion and recipe failed.

**Comment by kelson42** [comment]
> @rgaudin I tried your suggestion and recipe failed.

@RavanJAltaie If you talk about a tadk failing, please systematicalky put the link to the task.

**Comment by rgaudin** [comment]
@RavanJAltaie, please be mindful of our time:

- You asked how you could capture different languages, I still see only one recipe (for english) on the zimfarm
- You did not try the language suffix I suggested.
- Instead you tried a subdomain for some unknown reason.

Please request help from @benoit74 in the future, he's the one in charge of the scrapers now.

**Comment by benoit74** [comment]
To be clearer regarding @rgaudin suggestion: instead of using `https://alexandria.dk/` as an URL, use `https://alexandria.dk/en/`, `https://alexandria.dk/de/`, ...

**Comment by benoit74** [comment]
Why is this in production? I altered the recipe configuration to push to DEV, and removed the production file which is mostly totally broken.

**Comment by benoit74** [comment]
Twitter post regarding the license:

![Image](https://github.com/user-attachments/assets/27f86189-f165-4e99-801a-b5a686142958)

**Comment by Popolechien** [comment]
Weird output - tried again

**Comment by Popolechien** [comment]
Some links are incorrectly flagged as external, see e.g. https://dev.library.kiwix.org/viewer#alexandria.dk_en_all_2026-04a/alexandria.dk/en/data%3Fcon%3D2798 where clicking on `A second chance for wings` (first scenario link) should take us to a page from the site and it does not.

**Comment by benoit74** [comment]
I've fixed recipe and requested again, looks like it could be fine, tbc once completed in few days

**Comment by Popolechien** [comment]
Run failed https://farm.openzim.org/recipes/alexandria.dk_en_all

**Comment by benoit74** [comment]
Browser crashed, let's give it another try and if it fails again then we will have to give up for the time being until https://github.com/openzim/zimit/issues/436 is solved

**Comment by Popolechien** [comment]
Looks good! Pushing to PROD

**Comment by Popolechien** [comment]
Ok maybe not - a lot of files are missing for download, see for instance https://browse.library.kiwix.org/viewer#alexandria.dk_en_all_2026-09/alexandria.dk/en/data%3Fscenarie=19115

**Comment by benoit74** [comment]
Fixed hopefully, recipe restarted

**Comment by Popolechien** [comment]
Still the same error, with PDF documents failing to download, see e.g. [this one](https://browse.library.kiwix.org/content/alexandria.dk_en_all_2026-09a/alexandria.dk/download/scenario/18996/The%20Blessing%20-%20Velsignelsen%20Engelsk.pdf) at https://browse.library.kiwix.org/viewer#alexandria.dk_en_all_2026-09a/alexandria.dk/en/data%3Fscenarie=18996

**Comment by benoit74** [comment]
Why the ZIM is in production if it needs fixing? And it is not the same error, many PDFs are fine but some are indeed stopping at the middle of the download. This is weird, let me investigate.

**Comment by benoit74** [comment]
ZIM is probably fine, looks like we have an issue on production library preventing full PDFs download: https://github.com/kiwix/operations/issues/789

**Comment by benoit74** [comment]
PS: please do not move the book back to staging so that we can use this case to investigate the matter
